fix issue: AttributeError: 'module' object has no attribute 'ie' (#88)
* Update IE to Ie following name in selenium
* rename internet_explorer to ie
* fix flake8 unused warning